[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
neuralbond_solana_program = "UfQzdDXyS6huk6DTDKvvM5pTK2VtWQVmaGiNJ5qTJmo"

[programs.devnet]
neuralbond_solana_program = "UfQzdDXyS6huk6DTDKvvM5pTK2VtWQVmaGiNJ5qTJmo"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "localnet"
#wallet = "~/.config/solana/id.json"
cluster = "devnet"
wallet = "neuralbondowner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
